name: Post Test Results to ServiceNow 

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Run tests and generate results
        run: |
          mkdir -p test-results
          mvn test | tee test-results/results.log

      - name: Parse test results and send to ServiceNow
        run: |
          # Extract test results (simplified example)
          PASS_COUNT=$(grep -o 'Tests run: [0-9]*, Failures: 0' test-results/results.log | wc -l)
          FAIL_COUNT=$(grep -o 'Failures: [1-9]*' test-results/results.log | wc -l)
          
          # Post results to ServiceNow
          curl --request POST \
          --url https://<your_instance>.service-now.com/api/now/table/java_test_results \
          --header "Authorization: Bearer ${{ secrets.SERVICENOW_TOKEN }}" \
          --header "Content-Type: application/json" \
          --data '{
            "testName": "JUnit Tests",
            "status": "'"$([ "$FAIL_COUNT" -eq 0 ] && echo 'Pass' || echo 'Fail')"'", 
            "executionTime": "5 minutes", 
            "details": "'"$(cat test-results/results.log)"'"
          }'
